model_params:
  name: 'CoupledVAE'
  in_channels: 3
  latent_dim: 128

data_params:
  data_path: "/Users/igoroliveira/Downloads/CVAE/img_align_celeba"
  train_batch_size: 64
  val_batch_size: 64
  patch_size: 64
  num_workers: 4

exp_params:
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.0001
  manual_seed: 1265
  kappa: 0.001
  
trainer_params:
  max_epochs: 1
  #gradient_clip_val: 1.5
  #accumulate_grad_batches: 3  

logging_params:
  save_dir: "logs/"
  name: "coupledVAE"

